server:
  port: ${port:8082}

spring:
  application.name: MarineProducer
  jackson.deserialization.fail-on-unknown-properties: true
  cloud:
    zookeeper:
      discovery:
        enabled: true

  # Data creds
  datasource:
    url: jdbc:postgresql://localhost:5432/orfac
    username: orfac
    password: orfac
#    url: jdbc:postgresql://pg:5432/studs
#    username: s242395
#    password: *
  jpa.hibernate.ddl-auto: ${ddl:update}
  jpa.database: postgresql

marine.loadNewValues: ${load:true}


